language: php

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: COVERAGE=yes
    - php: 7.4snapshot
    - php: hhvm-3.30
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: hhvm-3.30
    - php: nightly
  fast_finish: true

before_install:
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || true; fi;

install:
  - export COMPOSER_FLAGS="--prefer-dist --no-interaction"
  - echo ${TRAVIS_PHP_VERSION}
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then export COMPOSER_FLAGS="$COMOPSER_FLAGS --ignore-platform-reqs"; fi
  - composer update $COMPOSER_FLAGS

script:
  - if [[ $COVERAGE = yes ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
  - if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
